# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Home"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Augmented Reality"
  weight = 20

[[main]]
  name = "Info "
  parent = "Augmented Reality"
  pageRef = "posts"
  weight = 25

[[main]]
  name = "Demos "
  parent = "Augmented Reality"
  pageRef = "posts"
  weight = 20

[[main]]
  name = "Games"
  weight = 20

[[main]]
  name = "Info"
  parent = "Games"
  pageRef = "posts"
  weight = 25

 [[main]]
  name = "Demos"
  parent = "Games"
  pageRef = "posts"
  weight = 20

  [[main]]
  name = "Pricing"
  weight = 200

  [[main]]
  name = "Contact"
  weight = 2010


#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

#[[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20
